### PR TITLE
Fixed most compilation warnings and a delay issue

### PR DESCRIPTION
**Pull request by qiwenmin**
* Fixed most compilation warnings (Compiler warning level: All)
* Fixed a delay issue in enc_read function.

Excellent work. Most are great. 
Let's take a little more look at the farhan's code such as encoder.
Thanks for your effort. Good!!!

DE Ian KD8CEC

### CODE REVIEW

**Comment by qiwenmin** [comment]
qiwenmin,
Thank you for your code check.
I understood what you wrote comment.
I do not think there is any worrying situation. My thoughts may be wrong, so if you have any other comments, you might want to add a comment.
So let's think about it.

millis() is an unsigned long type,  max value of unsigned long on arduino is 0xffffffff = 4294967295
and longType + intType = longType

unsigned long timeout_at = millis() + TIMEOUT;
if TIMEOUT = 2000, millis() = 1178000,  timeout_at = 1180000 (not ofverflow)
Suppose you ran uBITX for 49 days without turning it off.
Probably at this time overflow is possible.
if millis() =  4294967000 (49 days without turning it off), timeout = 2000
timeout_at is variable overflow = 1704

if (1704 < 4294967000) { process...} // some problem, problem is process with out delaytime

if we modified those code to if (millis() - start_at < TIMEOUT) {...}
if (4294967000 -  2000 < 4294967000) not overflow
but 2second after
if (4294967295 -  2000 < 4294967000)
.. rising overflow (millis() self) - first overflow of millis()
may be millis() value is 0 <-- i hasn't experiment
if (0 -  2000 < 4294967000) - variable overflow...
.
.
.
if (2000 -  2000 < 4294967000)  {processing logic}

Your opinion is very good. You will be able to delay the overflow time very little.
However, due to the nature of uBITX, I think it would be ok to keep the current code.
Thank you again for letting me discuss this again.

We are an amateur radio operator to learn together.

---------------------------------------------------------------------------------------------

Hello Dr. Lee,

I noticed there are many code sections for delay like this:

```c++
unsigned long timeout_at = millis() + TIMEOUT;

if (timeout_at < millis()) {...}
```

This should be wrong when `millis() + TIMEOUT` overflows. The code should be:

```c++
unsigned long start_at = millis();

if (millis() - start_at < TIMEOUT) {...}
```

There are some posts discussed this issue. For example: http://forum.arduino.cc/index.php?topic=375783.0

**Comment by phdlee** [comment]
For firmware stability, This pullrequest will be reflected in 0.29.
Most of the codes are perfect.
I applied it in my uBITX now and testing it. will merge to the end of the test.

Thanks for your effort

**Comment by qiwenmin** [comment]
Dr. Lee,

You are right. The overflow occurs every 49 days. I just want to make the codes perfect. The fix is not necessary.

But I think you may not get my thought. Think about the following condition:

At the beginning of the timeout 500ms, millis() returns 4294967195 (`MAX_LONG - 100`)

```
timeoutAt = millis() + 500  // it will overflow, the result will be 400

if (millis() > timeoutAt) ... // it will timeout immediately
```

In another way:

```
start_at = millis() // it is MAX_LONG - 100 -> 4294967195

if (millis() - start_at > 500) ... // it will not timeout until millis() returns the value greater than 400. This will always correct.
                                   // for example: if millis() rollovers to 0, (millis() - start_at) will be 100
                                   //              if millis() rollovers to 200, (millis() - start_at) will be 300
                                   //              if millis() rollovers to 300, (millis() - start_at) will be 400
                                   //              if millis() rollovers to 400, (millis() - start_at) will be 500
```

No matter what, I agree with you. If we do not pursue perfection, there is no need to modify.

de BG1REN

**Comment by phdlee** [comment]
Excellent!
I am very excited about this discussion.
I am looking for more interesting projects. I hope you will join the new project later.

Ian KD8CEC

**Comment by qiwenmin** [comment]
I am interested in your new project.

I am working on a small project now. It is about multitasking for embedded systems (Raduino). It is based on FSM (Finite State Machine) model for better timeout control and better task abstraction. Initially, I planned to start this project and rewrite the whole firmware when I got the ubitx, for fixing the cat issue of the original firmware. In my plan, it would use CI-V commands from ICOM (at that time, I only had ICOM CI-V commands manual).

Now I find your fork and have learned a lot from it. I will not rewrite the whole firmware probably. When I get the ubitx, I will try your fork. It's a wonderful work!

I am looking forward to working with you.

**Comment by phdlee** [comment]
Thanks for your effort

**Pull request merged**
